name: carijo_notes
description: A Local-First Markdown PKM for Desktop.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # State Management
  provider: ^6.0.5
  # Fonts
  google_fonts: ^6.1.0
  # Persistence
  shared_preferences: ^2.2.2
  # Markdown Rendering
  flutter_markdown: ^0.6.18
  markdown: ^7.1.1
  # Yaml for frontmatter
  yaml: ^3.1.2
  # Date formatting for Quick Capture
  intl: ^0.19.0
  # Icons
  cupertino_icons: ^1.0.2
  # File Picking
  file_picker: ^8.1.3
  # Path manipulation
  path: ^1.9.0
  # Supabase
  supabase_flutter: ^2.5.0
  # Database for indexing
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2
  flutter_math_fork: ^0.7.2
  # Audio Recording for STT
  record: ^5.1.0
  # HTTP for OpenAI API
  http: ^1.2.1
  # Secure Storage for Secrets
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true