name: carijo_notes
description: A Local-First Markdown PKM for Desktop.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # State Management
  provider: ^6.0.5
  # Fonts
  google_fonts: ^6.1.0
  # Persistence
  shared_preferences: ^2.2.2
  # Markdown Rendering
  flutter_markdown: ^0.6.18
  # Yaml for frontmatter
  yaml: ^3.1.2
  # Date formatting for Quick Capture
  intl: ^0.19.0
  # Icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true